### ISSUE TITLE
A few typos fixed

### ISSUE THREAD

**Issue by aoloe** [scribusproject/scribus#51]
since it's not possible to make pull requests for forks of forks (when you already forked the original repo) here my self pull request for a few typos in the otf tab:

https://github.com/aoloe/scribus-host/pull/2

**Comment by khaledhosny** [comment]
I merged it manually.

I think we can contact GitHub staff to unfork our repo, since we are not sending you PRs anyway.

**Comment by aoloe** [comment]
ooops, posted to the wrong repository, sorry... i wanted to put in the host-oman/scribus one. sorry.

i would suggest you not to unfork your repository: it's nice to see the link between the two.

and in my case, the problem is that i've already forked the scribusproject/scribus into my own account and wanted to fork yours...

and github does not really have solution for such situations.

i'm closing this ticket. thanks for merging the patch!

**Comment by khaledhosny** [comment]
[سبق السيف العذل](http://www.proz.com/kudoz/english_to_arabic/idioms_maxims_sayings/3534454-die_was_cast.html), or so to say. The repository is already unforked, you can always compare against master since we never touch it.

**Comment by aoloe** [comment]
the problem persists for me... since i have already forked a repository called "scribus" i cannot fork a second one with the same name.

not a big issue, even i've lost two hours because of this today :-)
(well, i've learned a few things in those two hours...)

**Comment by khaledhosny** [comment]
We would then need to rename the repository as well. Hmm, why not. OK, OK, I’ll wait a bit this time :)

**Comment by khaledhosny** [comment]
I guess you can rename your old fork, fork ours, rename it, rename the old one back.

**Comment by aoloe** [comment]
oh, yes, that would have worked!
my final idea was "rename the existing fork, fork host, make patch & pull request, wait for it being accepted, delete host fork, rename other fork" which i decided was too cumbersome to try and preferred putting a link in the wrong issue tracker :-)
so, don't rename your repository, i'll rename my fork of the fork as you wrote above!
right now.
(but i still dream of github answering my contact message and adding a dialog for renaming the new repository, when names conflict)
